- name: join host to tmm.lab with automatic reboot
  microsoft.ad.membership:
    dns_domain_name: tmm.lab
    hostname: '{{ inventory_hostname | lower }}'
    domain_admin_user: mark.xu
    domain_admin_password: P@ssword123!
    domain_ou_path: "OU=VIDM,DC=tmm,DC=lab"
    state: domain

- name: Reboot the machine if joining the domain requires a restart
  ansible.windows.win_reboot:
    reboot_timeout: 600
  when: domain_status.reboot_required