- name: Print distribution
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} - {{ ansible_distribution_version }}"
    
- name: Get Cluster IP
  ansible.builtin.include_tasks: get_cluster_ip.yml      

- name: Join Domain
  ansible.builtin.include_tasks: join_domain.yml    

- name: Initialise Disks
  ansible.builtin.include_tasks: init_disks.yml
  
- name: Install Software Components
  ansible.builtin.include_tasks: install_software.yml
  become: yes
  become_user: "tmm\\mark.xu"
  become_method: runas

- name: Setup iSCSI 
  ansible.builtin.include_tasks: iscsi.yml 
  become: yes
  become_user: "tmm\\mark.xu"
  become_method: runas
  
- name: Setup Cluster
  ansible.builtin.include_tasks: setup_cluster.yml
  become: yes
  become_user: "tmm\\mark.xu"
  become_method: runas 
   
- name: Set SQL Params
  ansible.builtin.include_tasks: sql_params.yml
  become: yes
  become_user: "tmm\\mark.xu"
  become_method: runas   
  
- name: Run DB Script
  ansible.builtin.include_tasks: sql_script_run.yml 
  when: mssql_service_info.services[0].state == 'started'
  become: yes
  become_user: "tmm\\mark.xu"
  become_method: runas                